version: '3.8'

services:
        nginx:
                image: nginx
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - /home/misterpki/nginx-docker/nginx.conf:/etc/nginx/nginx.conf
                        - /home/misterpki/nginx-docker/ssl:/ssl
